//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotSistemiMvc.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotlar
    {
        public int NotId { get; set; }
        public Nullable<byte> DersId { get; set; }
        public Nullable<int> OgrenciId { get; set; }
        public Nullable<byte> Sinav1 { get; set; }
        public Nullable<byte> Sinav2 { get; set; }
        public Nullable<byte> Sinav3 { get; set; }
        public Nullable<byte> Proje { get; set; }
        public Nullable<decimal> Ortalama { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual tblDersler tblDersler { get; set; }
        public virtual tblOgrenciler tblOgrenciler { get; set; }
    }
}
